### ISSUE TITLE
Does not work on select elements

### ISSUE THREAD

**Issue by maletor** [akaspin/jquery.f5#8]
In the HTML5, `select` elements can be validated too and should be considered [prey](https://github.com/akaspin/jquery.f5/blob/master/jquery.f5.js#L18).

http://dev.w3.org/html5/spec-author-view/the-select-element.html#the-select-element

**Comment by akaspin** [comment]
Thanks for issue. But I will be fully occupied for about a month. If this is so important to you, just fix this and send pull request to me.

**Comment by maletor** [comment]
I will try to find time and send a pull your way.
